kind: pipeline
type: docker
name: default

steps:
- name: build_docker
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t cppbuild .

- name: test
  image: cppbuild
  pull: if-not-exists
  commands:
  - mkdir build
  - cd build
  - cmake -Dpoaky_build_tests=ON -Dpoaky_build_coverage=ON ..
  - make poaky_test
  - ./bin/poaky_test
  - make poaky_coverage_report

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token: codecov_token

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
