kind: pipeline
type: docker
name: default

steps:
- name: build_docker
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t cppbuild .

- name: test
  image: cppbuild
  pull: if-not-exists
  commands:
  # Build
  - mkdir -p build
  - cd build
  - cmake -Drobintrace_build_tests=ON -Drobintrace_build_coverage=ON ..
  - make robintrace_test
  # Tests
  - ./bin/robintrace_test
  # Coverage report
  - make robintrace_coverage_report
  - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
  - curl -Os https://uploader.codecov.io/latest/alpine/codecov
  - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM
  - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM.sig
  - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
  - shasum -a 256 -c codecov.SHA256SUM
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN} -f robintrace_coverage_report.info
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
