kind: pipeline
type: docker
name: default

steps:
- name: build_docker
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t cppbuild .

- name: test
  image: cppbuild
  pull: if-not-exists
  commands:
  # Build
  - mkdir build
  - cd build
  - cmake -Dpoaky_build_tests=ON -Dpoaky_build_coverage=ON ..
  - make poaky_test
  # Tests
  - ./bin/poaky_test
  # Coverage report
  - make poaky_coverage_report
  - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
  - curl -Os https://uploader.codecov.io/latest/alpine/codecov
  - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM
  - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM.sig
  - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
  - shasum -a 256 -c codecov.SHA256SUM
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN} -f poaky_coverage_report.info
  # FOSSA license scan
  - cd ..
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash"
  - fossa analyze --detect-dynamic build/bin/poaky_test --experimental-link-project-binary build/bin/
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    FOSSA_API_KEY:
      from_secret: fossa_token

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
